apiVersion: 1
kind: Deployment
metadata:
  name: {{ .Values.api.name }}
spec:
  replica: {{ .Values.api.replica }}
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          # image: {{ .Values.api.image }}:{{ .Values.tag }}
          ports:
            - containerPort: 5000
      volumes:
        - name: thumbnails-vol
